@bi_api_HostAddress = https://localhost:8080

GET {{bi_api_HostAddress}}/calendar-events
Accept: application/json

###

GET {{bi_api_HostAddress}}/calendar-events?take=3&language=en
Accept: application/json

###
